In [1]:
'''

import numpy as np
import random
import math
import sys

with open("irisTrainData.txt", "r") as filestream:
    with open("irisTrainDataNew.txt", "w") as filestreamtwo :
        for line in filestream:
            currentline = line.split(",")
           # total = currentline[0] + currentline[1] + currentline + "\n"
            str1 = (currentline[1] + ',' + currentline[2]+ ',' + currentline[3]+ ',' + currentline[4]+ ',' + currentline[5] + ',' + 
                 currentline[6])
            filestreamtwo.write(str1)

with open("irisTestData.txt", "r") as filestreamTest:
    with open("irisTestDataNew.txt", "w") as filestreamTesttwo :
        for line in filestreamTest:
            currentline = line.split(",")
           # total = currentline[0] + currentline[1] + currentline + "\n"
            str1 = (currentline[1] + ',' + currentline[2]+ ',' + currentline[3]+ ',' + currentline[4]+ ',' + currentline[5] + ',' + 
                 currentline[6])
            filestreamTesttwo.write(str1)
'''

'\n\nimport numpy as np\nimport random\nimport math\nimport sys\n\nwith open("irisTrainData.txt", "r") as filestream:\n    with open("irisTrainDataNew.txt", "w") as filestreamtwo :\n        for line in filestream:\n            currentline = line.split(",")\n           # total = currentline[0] + currentline[1] + currentline + "\n"\n            str1 = (currentline[1] + \',\' + currentline[2]+ \',\' + currentline[3]+ \',\' + currentline[4]+ \',\' + currentline[5] + \',\' + \n                 currentline[6])\n            filestreamtwo.write(str1)\n\nwith open("irisTestData.txt", "r") as filestreamTest:\n    with open("irisTestDataNew.txt", "w") as filestreamTesttwo :\n        for line in filestreamTest:\n            currentline = line.split(",")\n           # total = currentline[0] + currentline[1] + currentline + "\n"\n            str1 = (currentline[1] + \',\' + currentline[2]+ \',\' + currentline[3]+ \',\' + currentline[4]+ \',\' + currentline[5] + \',\' + \n                 currentline

In [2]:
#adding noise
'''
import numpy as np 
mu, sigma = 0, 0.1 
# creating a noise with the same dimension as the dataset (2,2) 
noise = np.random.normal(mu, sigma, [30,7]) 
print(noise)

"""
print output: 
array([[-0.11114313,  0.25927152],
       [ 0.06701506, -0.09364186]])
"""
clean_signal = testDataMatrix
signal = clean_signal + noise
print(signal)
testmatrixWithNoise = signal
'''

'\nimport numpy as np \nmu, sigma = 0, 0.1 \n# creating a noise with the same dimension as the dataset (2,2) \nnoise = np.random.normal(mu, sigma, [30,7]) \nprint(noise)\n\n"""\nprint output: \narray([[-0.11114313,  0.25927152],\n       [ 0.06701506, -0.09364186]])\n"""\nclean_signal = testDataMatrix\nsignal = clean_signal + noise\nprint(signal)\ntestmatrixWithNoise = signal\n'

In [3]:
import numpy as np
import random
import math
import sys

#consider 10 items in training and test 
with open("irisTrainData.txt", "r") as filestream:
    with open("irisTrainDataNew2.txt", "w") as filestreamtwo :
        for line in filestream:
            currentline = line.split(",")
           # total = currentline[0] + currentline[1] + currentline + "\n"
            
            
            str1 = (currentline[0] + ',' + currentline[1]+ ',' + currentline[2]+ ',' + currentline[3]+
                    ',' + currentline[0] + ',' + currentline[1]+ ',' + currentline[2]+
                    ',' + currentline[4] + ',' +  currentline[5] +',' + currentline[6])
            str1 = (currentline[0] + ',' + currentline[1]+ ','  +  currentline[5] +',' + currentline[6])
            
            
            filestreamtwo.write(str1)
           

with open("irisTestData.txt", "r") as filestreamTest:
    with open("irisTestDataNew2.txt", "w") as filestreamTesttwo :
        for line in filestreamTest:
            currentline = line.split(",")
            # total = currentline[0] + currentline[1] + currentline + "\n"
            str1 = (currentline[0] + ',' + currentline[1]+ ','  +  currentline[5] +',' + currentline[6])
            
            filestreamTesttwo.write(str1)
             

In [5]:
# nn_backprop.py
# Python 3.x
#data (input=output=3, hidden=5)

import numpy as np
import random
import math
import sys

# helper functions

def loadFile(df):
  # load a comma-delimited text file into an np matrix
  resultList = []
  f = open(df, 'r')
  for line in f:
    line = line.rstrip('\n')  # "1.0,2.0,3.0"
    sVals = line.split(',')   # ["1.0", "2.0, "3.0"]
    fVals = list(map(np.float32, sVals))  # [1.0, 2.0, 3.0]
    resultList.append(fVals)  # [[1.0, 2.0, 3.0] , [4.0, 5.0, 6.0]]
  f.close()
  return np.asarray(resultList, dtype=np.float32)  # not necessary
# end loadFile
  
def showVector(v, dec):
  fmt = "%." + str(dec) + "f" # like %.4f
  for i in range(len(v)):
    x = v[i]
    if x >= 0.0: print(' ', end='')
    print(fmt % x + '  ', end='')
  print('')
  
def showMatrix(m, dec):
  fmt = "%." + str(dec) + "f" # like %.4f  
  for i in range(len(m)):
    for j in range(len(m[i])):
      x = m[i,j]
      if x >= 0.0: print(' ', end='')
      print(fmt % x + '  ', end='')
    print('')
	
def showMatrixPartial(m, numRows, dec, indices):
  fmt = "%." + str(dec) + "f" # like %.4f
  lastRow = len(m) - 1
  width = len(str(lastRow))
  for i in range(numRows):
    if indices == True:
      print("[", end='')
      print(str(i).rjust(width), end='')
      print("] ", end='')	  
  
    for j in range(len(m[i])):
      x = m[i,j]
      if x >= 0.0: print(' ', end='')
      print(fmt % x + '  ', end='')
    print('')
  print(" . . . ")

  if indices == True:
    print("[", end='')
    print(str(lastRow).rjust(width), end='')
    print("] ", end='')	  
  for j in range(len(m[lastRow])):
    x = m[lastRow,j]
    if x >= 0.0: print(' ', end='')
    print(fmt % x + '  ', end='')
  print('')	  
  
# -----
	
class NeuralNetwork:

  def __init__(self, numInput, numHidden, numOutput, seed):
    self.ni = numInput
    self.nh = numHidden
    self.no = numOutput
	
    self.iNodes = np.zeros(shape=[self.ni], dtype=np.float32)
    self.hNodes = np.zeros(shape=[self.nh], dtype=np.float32)
    self.oNodes = np.zeros(shape=[self.no], dtype=np.float32)
	
    self.ihWeights = np.zeros(shape=[self.ni,self.nh], dtype=np.float32)
    self.hoWeights = np.zeros(shape=[self.nh,self.no], dtype=np.float32)
	
    self.hBiases = np.zeros(shape=[self.nh], dtype=np.float32)
    self.oBiases = np.zeros(shape=[self.no], dtype=np.float32)
	
    self.rnd = random.Random(seed) # allows multiple instances
    self.initializeWeights()
 	
  def setWeights(self, weights):
    if len(weights) != self.totalWeights(self.ni, self.nh, self.no):
      print("Warning: len(weights) error in setWeights()")	

    idx = 0
    for i in range(self.ni):
      for j in range(self.nh):
        self.ihWeights[i,j] = weights[idx]
        idx += 1
		
    for j in range(self.nh):
      self.hBiases[j] = weights[idx]
      idx += 1

    for j in range(self.nh):
      for k in range(self.no):
        self.hoWeights[j,k] = weights[idx]
        idx += 1
	  
    for k in range(self.no):
      self.oBiases[k] = weights[idx]
      idx += 1
	  
  def getWeights(self):
    tw = self.totalWeights(self.ni, self.nh, self.no)
    result = np.zeros(shape=[tw], dtype=np.float32)
    idx = 0  # points into result
    
    for i in range(self.ni):
      for j in range(self.nh):
        result[idx] = self.ihWeights[i,j]
        idx += 1
		
    for j in range(self.nh):
      result[idx] = self.hBiases[j]
      idx += 1

    for j in range(self.nh):
      for k in range(self.no):
        result[idx] = self.hoWeights[j,k]
        idx += 1
	  
    for k in range(self.no):
      result[idx] = self.oBiases[k]
      idx += 1
	  
    return result
 	
  def initializeWeights(self):
    numWts = self.totalWeights(self.ni, self.nh, self.no)
    wts = np.zeros(shape=[numWts], dtype=np.float32)
    lo = -0.01; hi = 0.01
    for idx in range(len(wts)):
      wts[idx] = (hi - lo) * self.rnd.random() + lo
    self.setWeights(wts)

  def computeOutputs(self, xValues):
    hSums = np.zeros(shape=[self.nh], dtype=np.float32)
    oSums = np.zeros(shape=[self.no], dtype=np.float32)

    for i in range(self.ni):
      self.iNodes[i] = xValues[i]

    for j in range(self.nh):
      for i in range(self.ni):
        hSums[j] += self.iNodes[i] * self.ihWeights[i,j]

    for j in range(self.nh):
      hSums[j] += self.hBiases[j]
	  
    for j in range(self.nh):
      self.hNodes[j] = self.hypertan(hSums[j])

    for k in range(self.no):
      for j in range(self.nh):
        oSums[k] += self.hNodes[j] * self.hoWeights[j,k]

    for k in range(self.no):
      oSums[k] += self.oBiases[k]
 
    softOut = self.softmax(oSums)
    for k in range(self.no):
      self.oNodes[k] = softOut[k]
	  
    result = np.zeros(shape=self.no, dtype=np.float32)
    for k in range(self.no):
      result[k] = self.oNodes[k]
	  
    return result
	
  def train(self, trainData, maxEpochs, learnRate):
    print("inside train")
    #print("inside train", self.ni)
    #print("inside train", self.nh)
   # print("inside train", self.no)
    #print("inside train trainData", trainData)
    hoGrads = np.zeros(shape=[self.nh, self.no], dtype=np.float32)  # hidden-to-output weights gradients
    obGrads = np.zeros(shape=[self.no], dtype=np.float32)  # output node biases gradients
    ihGrads = np.zeros(shape=[self.ni, self.nh], dtype=np.float32)  # input-to-hidden weights gradients
    hbGrads = np.zeros(shape=[self.nh], dtype=np.float32)  # hidden biases gradients
	
    oSignals = np.zeros(shape=[self.no], dtype=np.float32)  # output signals: gradients w/o assoc. input terms
    hSignals = np.zeros(shape=[self.nh], dtype=np.float32)  # hidden signals: gradients w/o assoc. input terms

    epoch = 0
    x_values = np.zeros(shape=[self.ni], dtype=np.float32)
    t_values = np.zeros(shape=[self.no], dtype=np.float32)
    numTrainItems = len(trainData)
    indices = np.arange(numTrainItems)  # [0, 1, 2, . . n-1]  # rnd.shuffle(v)

    while epoch < maxEpochs:
      self.rnd.shuffle(indices)  # scramble order of training items
      for ii in range(numTrainItems):
        idx = indices[ii]
        #print("inside train idx", idx)
        for j in range(self.ni):
          x_values[j] = trainData[idx, j]  # get the input values	
        for j in range(self.no):
          #print("inside train j+self.ni", j+self.ni)
          t_values[j] = trainData[idx, j+self.ni]  # get the target values
        self.computeOutputs(x_values)  # results stored internally
		
        # 1. compute output node signals
        for k in range(self.no):
          derivative = (1 - self.oNodes[k]) * self.oNodes[k]  # softmax
          oSignals[k] = derivative * (self.oNodes[k] - t_values[k])  # E=(t-o)^2 do E'=(o-t)

        # 2. compute hidden-to-output weight gradients using output signals
        for j in range(self.nh):
          for k in range(self.no):
            hoGrads[j, k] = oSignals[k] * self.hNodes[j]
			
        # 3. compute output node bias gradients using output signals
        for k in range(self.no):
          obGrads[k] = oSignals[k] * 1.0  # 1.0 dummy input can be dropped
		  
        # 4. compute hidden node signals
        for j in range(self.nh):
          sum = 0.0
          for k in range(self.no):
            sum += oSignals[k] * self.hoWeights[j,k]
          derivative = (1 - self.hNodes[j]) * (1 + self.hNodes[j])  # tanh activation
          hSignals[j] = derivative * sum
		 
        # 5 compute input-to-hidden weight gradients using hidden signals
        for i in range(self.ni):
          for j in range(self.nh):
            ihGrads[i, j] = hSignals[j] * self.iNodes[i]

        # 6. compute hidden node bias gradients using hidden signals
        for j in range(self.nh):
          hbGrads[j] = hSignals[j] * 1.0  # 1.0 dummy input can be dropped

        # update weights and biases using the gradients
		
        # 1. update input-to-hidden weights
        for i in range(self.ni):
          for j in range(self.nh):
            delta = -1.0 * learnRate * ihGrads[i,j]
            self.ihWeights[i, j] += delta
			
        # 2. update hidden node biases
        for j in range(self.nh):
          delta = -1.0 * learnRate * hbGrads[j]
          self.hBiases[j] += delta      
		  
        # 3. update hidden-to-output weights
        for j in range(self.nh):
          for k in range(self.no):
            delta = -1.0 * learnRate * hoGrads[j,k]
            self.hoWeights[j, k] += delta
			
        # 4. update output node biases
        for k in range(self.no):
          delta = -1.0 * learnRate * obGrads[k]
          self.oBiases[k] += delta
 		  
      epoch += 1
	  
      if epoch % 10 == 0:
        mse = self.meanSquaredError(trainData)
        print("epoch = " + str(epoch) + " ms error = %0.4f " % mse)
    # end while
    
    result = self.getWeights()
    return result,self.hoWeights,self.ihWeights
  # end train
    
  def computeOutputs_AlteredWeights(self, xValues,ihWeightsNew,hoWeightsNew):
        hSums = np.zeros(shape=[self.nh], dtype=np.float32)
        oSums = np.zeros(shape=[self.no], dtype=np.float32)

        for i in range(self.ni):
            self.iNodes[i] = xValues[i]

        for j in range(self.nh):
            for i in range(self.ni):
                hSums[j] += self.iNodes[i] * ihWeightsNew[i,j]

        for j in range(self.nh):
            hSums[j] += self.hBiases[j]
 
        for j in range(self.nh):
            self.hNodes[j] = self.hypertan(hSums[j])

        for k in range(self.no):
            for j in range(self.nh):
                oSums[k] += self.hNodes[j] * hoWeightsNew[j,k]

        for k in range(self.no):
            oSums[k] += self.oBiases[k]
 
        softOut = self.softmax(oSums)
        for k in range(self.no):
            self.oNodes[k] = softOut[k]
  
        result = np.zeros(shape=self.no, dtype=np.float32)
        for k in range(self.no):
            result[k] = self.oNodes[k]
 
        return result


  def accuracy_AlteredWeights(self, tdata, ihWeightsNew, hoWeightsNew):  # train or test data matrix
        num_correct = 0; num_wrong = 0
        x_values = np.zeros(shape=[self.ni], dtype=np.float32)
        t_values = np.zeros(shape=[self.no], dtype=np.float32)

        for i in range(len(tdata)):  # walk thru each data item
            for j in range(self.ni):  # peel off input values from curr data row 
                x_values[j] = tdata[i,j]
            for j in range(self.no):  # peel off tareget values from curr data row
                t_values[j] = tdata[i, j+self.ni]

            y_values = self.computeOutputs_AlteredWeights(x_values,ihWeightsNew,hoWeightsNew)  # computed output values)
            max_index = np.argmax(y_values)  # index of largest output value 

            if abs(t_values[max_index] - 1.0) < 1.0e-5:
                num_correct += 1
            else:
                num_wrong += 1

        return (num_correct * 1.0) / (num_correct + num_wrong)
    
  def accuracy(self, tdata):  # train or test data matrix
    num_correct = 0; num_wrong = 0
    x_values = np.zeros(shape=[self.ni], dtype=np.float32)
    t_values = np.zeros(shape=[self.no], dtype=np.float32)

    for i in range(len(tdata)):  # walk thru each data item
      for j in range(self.ni):  # peel off input values from curr data row 
        x_values[j] = tdata[i,j]
      for j in range(self.no):  # peel off tareget values from curr data row
        t_values[j] = tdata[i, j+self.ni]

      y_values = self.computeOutputs(x_values)  # computed output values)
      max_index = np.argmax(y_values)  # index of largest output value 

      if abs(t_values[max_index] - 1.0) < 1.0e-5:
        num_correct += 1
      else:
        num_wrong += 1

    return (num_correct * 1.0) / (num_correct + num_wrong)

  def meanSquaredError(self, tdata):  # on train or test data matrix
    sumSquaredError = 0.0
    x_values = np.zeros(shape=[self.ni], dtype=np.float32)
    t_values = np.zeros(shape=[self.no], dtype=np.float32)

    for ii in range(len(tdata)):  # walk thru each data item
      for jj in range(self.ni):  # peel off input values from curr data row 
        x_values[jj] = tdata[ii, jj]
      for jj in range(self.no):  # peel off tareget values from curr data row
        t_values[jj] = tdata[ii, jj+self.ni]

      y_values = self.computeOutputs(x_values)  # computed output values
	  
      for j in range(self.no):
        err = t_values[j] - y_values[j]
        sumSquaredError += err * err  # (t-o)^2
		
    return sumSquaredError / len(tdata)

  def pairwiseswap(self,lst):
        #print("in pairwiseswap" +lst)
        def swap(l1):
            #print("in swap")
            res = []
            #print("l1 len", len(l1))
            for i in range(0,len(l1)-1,2):
                res.append(l1[i+1])
                res.append(l1[i])
            #print("res", res)
            return res

        res = []
        if len(lst)%2==0:
            #print("ev")
            res = swap(lst)            
        else:
            #print("od")
            res = swap(lst)
            res.append(lst[len(lst)-1])
        return res
    
  def pairwiseswap1_reduced(self, lst):
        #print("in pairwiseswap" +lst)
        def swap(l1):
            #print("in swap")
            res = []
            swapOnce = False
            #print("l1 len", len(l1))
            for i in range(0,len(l1)-1,2):
                #print("i=",i)
                #print("swapOnce=",swapOnce)
                if(i==0 and swapOnce == False):
                    swapOnce = True
                    res.append(l1[i+1])
                    res.append(l1[i])
                else :
                    res.append(l1[i])
                    res.append(l1[i+1])
            #print("res", res)
            return res

        res = []
        if len(lst)%2==0:
            #print("ev")
            res = swap(lst)            
        else:
            #print("od")
            res = swap(lst)
            res.append(lst[len(lst)-1])
        return res       
  
  def pairwiseswap2_all(lst):
        #print("in pairwiseswap" +lst)
        def swap(l1):
            #print("in swap")
            res = []
            swapOnce = False
            #print("l1 len", len(l1))
            if(len(l1) <=3) :
                for i in range(0,len(l1)-1,2):
                    print("i=",i)
                    print("swapOnce=",swapOnce)
                    if(i==0 and swapOnce == False):
                        swapOnce = True
                        res.append(l1[i+1])
                        res.append(l1[i])
                    else :
                        res.append(l1[i])
                        res.append(l1[i+1])
            else :
                for i in range(0,len(l1)-1,2):
                    print("i=",i)
                    print("swapOnce=",swapOnce)
                    if(i==2 and swapOnce == False):
                        swapOnce = True
                        res.append(l1[i+1])
                        res.append(l1[i])
                    else :
                        res.append(l1[i])
                        res.append(l1[i+1])
            #print("res", res)
            return res

        res = []
        if len(lst)%2==0:
            #print("ev")
            res = swap(lst)            
        else:
            #print("od")
            res = swap(lst)
            res.append(lst[len(lst)-1])
        return res
    
  @staticmethod
  def hypertan(x):
    if x < -20.0:
      return -1.0
    elif x > 20.0:
      return 1.0
    else:
      return math.tanh(x)

  @staticmethod	  
  def softmax(oSums):
    result = np.zeros(shape=[len(oSums)], dtype=np.float32)
    m = max(oSums)
    divisor = 0.0
    for k in range(len(oSums)):
       divisor += math.exp(oSums[k] - m)
    for k in range(len(result)):
      result[k] =  math.exp(oSums[k] - m) / divisor
    return result
	
  @staticmethod
  def totalWeights(nInput, nHidden, nOutput):
   tw = (nInput * nHidden) + (nHidden * nOutput) + nHidden + nOutput
   return tw

# end class NeuralNetwork

def main():
  print("\nBegin NN back-propagation demo \n")
  pv = sys.version
  npv = np.version.version 
  print("Using Python version " + str(pv) +
    "\n and NumPy version "  + str(npv))
  
  numInput = 4# 3
  numHidden = 50#5
  numOutput = 3 #3
  print("\nCreating a %d-%d-%d neural network " %
    (numInput, numHidden, numOutput) )
  nn = NeuralNetwork(numInput, numHidden, numOutput, seed=3)
  
  print("\nLoading Iris training and test data ")
  trainDataPath = "irisTrainData.txt" #"irisTrainDataEven.txt"#"irisTrainData.txt" #irisTrainDataNew2
  trainDataMatrix = loadFile(trainDataPath)
  print("\nTest data: ")
  showMatrixPartial(trainDataMatrix, 4, 1, True)
  testDataPath = "irisTestData.txt"# "irisTestDataEven.txt"#"irisTestData.txt" #irisTestDataNew2
  testDataMatrix = loadFile(testDataPath)
  
  maxEpochs = 50
  learnRate = 0.01
  print("\nSetting maxEpochs = " + str(maxEpochs))
  print("Setting learning rate = %0.3f " % learnRate)
  print("\nStarting training")
  res,hoW, ihW  =  nn.train(trainDataMatrix, maxEpochs, learnRate)
  print("Training complete")
  print("res sh",res.shape)
  
  print("ihW sh",ihW.shape)
  print("hoW sh",hoW.shape)
  #print("res",res)
  
  print("ihW",ihW)
  print("hoW",hoW)


  accTrain = nn.accuracy(trainDataMatrix)
  accTest = nn.accuracy(testDataMatrix)

  print("\nAccuracy on 120-item train data = %0.4f " % accTrain)
  print("Accuracy on 30-item test data   = %0.4f " % accTest)

  print("\nEnd demo \n")
  
  print("ihWeights:")  
  #print(ihW)
  print("hoWeights:")  
  #print(hoW)
  


  print("Case 1 : Sign Flip Starts ")
  #a=np.array(hoW)
  hoWeightsSignChanged = -hoW
  #b=np.array(ihW)
  ihWeightsSignChanged = -ihW
  print("ihWeightsSignChanged:")
  print(ihWeightsSignChanged)
  print("hoWeightsSignChanged:")
  print(hoWeightsSignChanged)
  
  #tbc
  
  accTrain_SignFlip = nn.accuracy_AlteredWeights(trainDataMatrix,ihWeightsSignChanged,hoWeightsSignChanged)
  accTest_SignFlip = nn.accuracy_AlteredWeights(testDataMatrix,ihWeightsSignChanged,hoWeightsSignChanged)

  
  #print("\nAccuracy with  SignFlip  on 120-item train data = %0.4f " % accTrain_SignFlip)
  print("Accuracy with SignFlip  on 30-item test data   = %0.4f " % accTest_SignFlip)
  print("Case 1 : Sign Flip Ends ")
  
  
  print("Case 2 : Swap Hidden Weights Starts ")
  #a=np.array(hoW)
  
  ihWeightsSwapped = []
  b = ihW
  print("b==ihW=",b)
  for k in range(len(b)): 
      ihWeightsSwapped.append(nn.pairwiseswap(b[k]))
      #ihWeightsSwapped.append(nn.pairwiseswap1_reduced(b[k]))
      
    
    
  hoWeightsSwapped = []
  a = hoW
  print("a==hoW=",a)
  for k in range(len(a)):  
      hoWeightsSwapped.append(nn.pairwiseswap(a[k]))
      #hoWeightsSwapped.append(nn.pairwiseswap1_reduced(a[k]))

  
  
    
  ihWeightsSwapped = np.array(ihWeightsSwapped)
  hoWeightsSwapped = np.array(hoWeightsSwapped)
  print("ihWeightsSwapped:")
  print(ihWeightsSwapped)  

  print("hoWeightsSwapped:")
  print(hoWeightsSwapped)
 
  #tbc
  
  accTrain_WeightsSwap = nn.accuracy_AlteredWeights(trainDataMatrix,ihWeightsSwapped,hoWeightsSwapped)
  accTest_WeightsSwap = nn.accuracy_AlteredWeights(testDataMatrix,ihWeightsSwapped,hoWeightsSwapped)

  
  #print("\nAccuracy with  swapped weights  on 120-item train data = %0.4f " % accTrain_SignFlip)
  print("Accuracy with swapped weights  on 30-item test data   = %0.4f " % accTest_SignFlip)
  
  print("Case 1 : Swap Hidden Weights Ends ")
  
  print("test")
  accTrain_1 = nn.accuracy_AlteredWeights(trainDataMatrix,ihW,hoW)
  accTest_1 = nn.accuracy_AlteredWeights(testDataMatrix,ihW,hoW)
  #print("\nAccuracy on 120-item train data = %0.4f " % accTrain_1)
  print("Accuracy on 30-item test data   = %0.4f " % accTest_1)
    
  '''
  print("for noisy data")

  mu, sigma = 0, 0.01 
  # creating a noise with the same dimension as the dataset (2,2) 
  noise = np.random.normal(mu, sigma, [30,7]) 
  print(noise)

 
  clean_signal = testDataMatrix
  signal = clean_signal + noise
  print(signal)
  testmatrixWithNoise = signal
  #print("\nAccuracy on 120-item train data = %0.4f " % accTrain_1)
  accTest_2 = nn.accuracy(testmatrixWithNoise)
  print("Accuracy on 30-item noisy test data   = %0.4f " % accTest_2)
  '''
  print("\nEnd demo \n")
   
if __name__ == "__main__":
  main()

# end script


Begin NN back-propagation demo 

Using Python version 3.6.4 |Anaconda, Inc.| (default, Mar 12 2018, 20:20:50) [MSC v.1900 64 bit (AMD64)]
 and NumPy version 1.16.2

Creating a 4-50-3 neural network 

Loading Iris training and test data 

Test data: 
[  0]  5.1   3.5   1.4   0.2   1.0   0.0   0.0  
[  1]  4.9   3.0   1.4   0.2   1.0   0.0   0.0  
[  2]  4.7   3.2   1.3   0.2   1.0   0.0   0.0  
[  3]  4.6   3.1   1.5   0.2   1.0   0.0   0.0  
 . . . 
[119]  6.9   3.1   5.4   2.1   0.0   0.0   1.0  

Setting maxEpochs = 50
Setting learning rate = 0.010 

Starting training
inside train
epoch = 10 ms error = 0.6030 
epoch = 20 ms error = 0.3297 
epoch = 30 ms error = 0.2652 
epoch = 40 ms error = 0.1986 
epoch = 50 ms error = 0.1514 
Training complete
res sh (403,)
ihW sh (4, 50)
hoW sh (50, 3)
ihW [[-7.41325244e-02  2.65321899e-02  6.83007985e-02 -1.38492426e-02
   1.13626570e-02 -6.21924475e-02 -3.34476829e-02  4.56529520e-02
   1.01948582e-01  1.07460119e-01 -5.50385043e-02 -5.10007329

In [4]:
print('hi')

hi


In [6]:
#test swap
def pairwiseswap1(self,lst):
        def swap(l1):
            print("swap")
            print("l1")
            res = []
            for i in range(0,len(l1)-1,2):
                res.append(l1[i+1])
                res.append(l1[i])
            return res

        res = []
        if len(lst)%2==0:
            print("in ev")
            res = swap(lst)
        else:
            res = swap(lst)
            res.append(lst[len(lst)-1])
        return res


In [ ]:
def pairwiseswap1_reduced(self, lst):
        #print("in pairwiseswap" +lst)
        def swap(l1):
            #print("in swap")
            res = []
            swapOnce = False
            #print("l1 len", len(l1))
            for i in range(0,len(l1)-1,2):
                #print("i=",i)
                #print("swapOnce=",swapOnce)
                if(i==0 and swapOnce == False):
                    swapOnce = True
                    res.append(l1[i+1])
                    res.append(l1[i])
                else :
                    res.append(l1[i])
                    res.append(l1[i+1])
            #print("res", res)
            return res

        res = []
        if len(lst)%2==0:
            #print("ev")
            res = swap(lst)            
        else:
            #print("od")
            res = swap(lst)
            res.append(lst[len(lst)-1])
        return res 

In [71]:
def pairwiseswap2_reduced(lst):
        #print("in pairwiseswap" +lst)
        def swap(l1):
            #print("in swap")
            res = []
            swapOnce = False
            #print("l1 len", len(l1))
            if(len(l1) <=3) :
                for i in range(0,len(l1)-1,2):
                    print("i=",i)
                    print("swapOnce=",swapOnce)
                    if(i==0 and swapOnce == False):
                        swapOnce = True
                        res.append(l1[i+1])
                        res.append(l1[i])
                    else :
                        res.append(l1[i])
                        res.append(l1[i+1])
            else :
                for i in range(0,len(l1)-1,2):
                    print("i=",i)
                    print("swapOnce=",swapOnce)
                    if(i==2 and swapOnce == False):
                        swapOnce = True
                        res.append(l1[i+1])
                        res.append(l1[i])
                    else :
                        res.append(l1[i])
                        res.append(l1[i+1])
            #print("res", res)
            return res

        res = []
        if len(lst)%2==0:
            #print("ev")
            res = swap(lst)            
        else:
            #print("od")
            res = swap(lst)
            res.append(lst[len(lst)-1])
        return res

In [21]:
def pairwiseswapToroidal(lst):
        def swap(l1):
            print("swap")
            print("l1")
            res = []
            print(len(l1))
            for i in range(0,len(l1)):
                print(i)
                
                if i == len(l1)-1:
                    res.append(l1[0])
                else :
                    res.append(l1[i+1])
            return res

        
        res = []
        res = swap(lst)
        '''
        if len(lst)%2==0:
            print("in ev")
            res = swap(lst)
        else:
            res = swap(lst)
            res.append(lst[len(lst)-1])
        '''
        return res

In [22]:
#c=  [[ 1.0766397, -0.11083151, -1.345182, 1.055, 2.55],[11,15,13,14,12]]
c= [[ 1.411012,    2.1886458,  -1.6560197,   2.090276,    0.89395714,],
 [-0.6751054,  -0.99360114,  0.7654133,  -0.9368092,  -1.0570005 ],
 [-1.6931396 , -2.4050577,   1.9510872,  -2.3446977,  -0.5585038 ]]


In [77]:
c= [[ 1.0766397,  -0.11083151, -1.345182  ],
 [ 1.2192099,   0.26164526, -1.8310475 ],
 [-0.93926555, -0.48345995,  1.7738097 ],
 [ 0.8293996,   0.74785477, -1.8291305 ],
 [ 2.39011,   -2.4308527,  -0.4801488 ]]

In [23]:
nSwapped = []
for k in range(len(c)):    
      print("in for", k)
      print("ck",c[k])
      print("typeck",type(c[k]))
      nSwapped.append(pairwiseswapToroidal(c[k]))
print(nSwapped)

in for 0
ck [1.411012, 2.1886458, -1.6560197, 2.090276, 0.89395714]
typeck <class 'list'>
swap
l1
5
0
1
2
3
4
in for 1
ck [-0.6751054, -0.99360114, 0.7654133, -0.9368092, -1.0570005]
typeck <class 'list'>
swap
l1
5
0
1
2
3
4
in for 2
ck [-1.6931396, -2.4050577, 1.9510872, -2.3446977, -0.5585038]
typeck <class 'list'>
swap
l1
5
0
1
2
3
4
[[2.1886458, -1.6560197, 2.090276, 0.89395714, 1.411012], [-0.99360114, 0.7654133, -0.9368092, -1.0570005, -0.6751054], [-2.4050577, 1.9510872, -2.3446977, -0.5585038, -1.6931396]]


In [78]:
nSwapped = []
for k in range(len(c)):    
      print("in for", k)
      print("ck",c[k])
      print("typeck",type(c[k]))
      nSwapped.append(pairwiseswap2_reduced(c[k]))
print(nSwapped)

in for 0
ck [1.0766397, -0.11083151, -1.345182]
typeck <class 'list'>
i= 0
swapOnce= False
in for 1
ck [1.2192099, 0.26164526, -1.8310475]
typeck <class 'list'>
i= 0
swapOnce= False
in for 2
ck [-0.93926555, -0.48345995, 1.7738097]
typeck <class 'list'>
i= 0
swapOnce= False
in for 3
ck [0.8293996, 0.74785477, -1.8291305]
typeck <class 'list'>
i= 0
swapOnce= False
in for 4
ck [2.39011, -2.4308527, -0.4801488]
typeck <class 'list'>
i= 0
swapOnce= False
[[-0.11083151, 1.0766397, -1.345182], [0.26164526, 1.2192099, -1.8310475], [-0.48345995, -0.93926555, 1.7738097], [0.74785477, 0.8293996, -1.8291305], [-2.4308527, 2.39011, -0.4801488]]


In [6]:
testDataPath = "irisTestData.txt"# "irisTestDataEven.txt"#"irisTestData.txt" #irisTestDataNew2
testDataMatrix = loadFile(testDataPath)

print(testDataMatrix)

[[5.  3.5 1.3 0.3 1.  0.  0. ]
 [4.5 2.3 1.3 0.3 1.  0.  0. ]
 [4.4 3.2 1.3 0.2 1.  0.  0. ]
 [5.  3.5 1.6 0.6 1.  0.  0. ]
 [5.1 3.8 1.9 0.4 1.  0.  0. ]
 [4.8 3.  1.4 0.3 1.  0.  0. ]
 [5.1 3.8 1.6 0.2 1.  0.  0. ]
 [4.6 3.2 1.4 0.2 1.  0.  0. ]
 [5.3 3.7 1.5 0.2 1.  0.  0. ]
 [5.  3.3 1.4 0.2 1.  0.  0. ]
 [5.5 2.6 4.4 1.2 0.  1.  0. ]
 [6.1 3.  4.6 1.4 0.  1.  0. ]
 [5.8 2.6 4.  1.2 0.  1.  0. ]
 [5.  2.3 3.3 1.  0.  1.  0. ]
 [5.6 2.7 4.2 1.3 0.  1.  0. ]
 [5.7 3.  4.2 1.2 0.  1.  0. ]
 [5.7 2.9 4.2 1.3 0.  1.  0. ]
 [6.2 2.9 4.3 1.3 0.  1.  0. ]
 [5.1 2.5 3.  1.1 0.  1.  0. ]
 [5.7 2.8 4.1 1.3 0.  1.  0. ]
 [6.7 3.1 5.6 2.4 0.  0.  1. ]
 [6.9 3.1 5.1 2.3 0.  0.  1. ]
 [5.8 2.7 5.1 1.9 0.  0.  1. ]
 [6.8 3.2 5.9 2.3 0.  0.  1. ]
 [6.7 3.3 5.7 2.5 0.  0.  1. ]
 [6.7 3.  5.2 2.3 0.  0.  1. ]
 [6.3 2.5 5.  1.9 0.  0.  1. ]
 [6.5 3.  5.2 2.  0.  0.  1. ]
 [6.2 3.4 5.4 2.3 0.  0.  1. ]
 [5.9 3.  5.1 1.8 0.  0.  1. ]]


In [19]:
import numpy as np 
mu, sigma = 0, 0.01 
# creating a noise with the same dimension as the dataset (2,2) 
noise = np.random.normal(mu, sigma, [30,4]) 
print(noise)

"""
print output: 
array([[-0.11114313,  0.25927152],
       [ 0.06701506, -0.09364186]])
"""
clean_signal = testDataMatrix
signal = clean_signal + noise
print(signal)

[[-9.10608025e-03  1.84413429e-03  1.31598109e-02  1.73151022e-02]
 [-5.67819384e-03 -7.50446057e-03 -1.16847250e-02  1.54403663e-03]
 [-5.97400136e-03  6.32999826e-03  2.03457692e-02 -2.54091849e-02]
 [ 6.42280429e-03 -2.38884840e-02 -3.38927966e-03  6.04919322e-03]
 [ 2.82603003e-04  2.47375050e-02  2.83253113e-03  1.00523297e-02]
 [-4.46780047e-03  1.57111366e-03  6.56893462e-03 -7.30275331e-03]
 [ 1.11352047e-02 -7.82705591e-03  2.57701095e-03 -1.26100424e-02]
 [ 2.10189850e-02  1.09768634e-02 -5.02817788e-03  1.48963966e-03]
 [-2.58464511e-02 -1.52710936e-02  1.88821988e-03 -4.15738283e-03]
 [ 6.56333270e-03  2.74261592e-03 -1.30563603e-02  4.44921738e-03]
 [-6.24348480e-03  9.85592213e-03 -1.50994056e-03 -7.57522569e-03]
 [ 4.46807450e-03 -6.94555616e-03  1.73961828e-02 -1.29797160e-02]
 [ 2.22219293e-02  3.69433080e-03 -9.30910873e-03 -1.77035871e-03]
 [ 3.93859007e-03  6.39946647e-03 -3.83087225e-03  2.09190721e-02]
 [ 1.20571539e-03  2.49329756e-02 -7.67385829e-03  1.63241505e

ValueError: operands could not be broadcast together with shapes (30,7) (30,4) 

In [9]:
 accTest = nn.accuracy(signal)

NameError: name 'nn' is not defined